[tool.poetry]
name = "fastapi-obs"
version = "0.1.0"
description = ""
authors = ["everysoftware <pravitel2015ify@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
